// src/types/extraction-types.ts 확장
import { BaseExtractionResult } from './extraction';
import { MediaAnalysisResult, MediaDetectionResult } from './media-analysis';

export interface VideoExtractionResult extends BaseExtractionResult {
  mediaType: 'video';
  mediaMetadata: {
    duration: number;
    viewCount: number;
    chapters: Array<{
      timestamp: string;
      title: string;
      description: string;
      startTime: number;
      endTime: number;
    }>;
    thumbnails: string[];
    tags: string[];
    category: string;
    transcript: string;
    hasTranscript: boolean;
  };
  aiAnalysis?: any;
  aiAnalysisError?: string;
  videoAnalysisError?: string;
}

export interface WebExtractionResult extends BaseExtractionResult {
  mediaType: 'text' | 'audio' | 'image';
  scrapingError?: string;
  mercuryError?: string;
  videoAnalysisError?: string;
}

// 🆕 확장된 미디어 추출 결과
export interface EnhancedMediaExtractionResult extends BaseExtractionResult {
  isMediaContent: boolean;
  mediaDetection?: MediaDetectionResult;
  mediaAnalysis?: MediaAnalysisResult;

  // 기존 필드들
  hasVideo?: boolean;
  hasAudio?: boolean;
  mediaDuration?: number;

  // 새로운 미디어 관련 필드들
  platform?: string;
  mediaId?: string;
  embedUrl?: string;
  thumbnailUrl?: string;
  channelName?: string;
  channelUrl?: string;
  uploadDate?: string;
  viewCount?: number;
  likeCount?: number;
  subtitles?: Array<{
    language: string;
    languageCode: string;
    isAutoGenerated: boolean;
    url?: string;
  }>;

  // 분석 메타데이터
  // 분석 메타데이터
  analysisMethod?: 'basic' | 'detailed' | 'comprehensive';
  analysisTimestamp?: string;
  analysisConfidence?: number;
  extractionErrors?: string[];

  // 타임라인 관련
  hasTimeline?: boolean;
  timelineSegments?: number;

  // 품질 정보
  quality?: {
    resolution?: string;
    bitrate?: number;
    fps?: number;
    audioQuality?: string;
    codec?: string;
  };
}

// 🆕 미디어 추출 옵션
export interface MediaExtractionOptions {
  includeTranscript?: boolean;
  includeChapters?: boolean;
  includeThumbnails?: boolean;
  includeMetadata?: boolean;
  preferredLanguage?: string;
  maxDuration?: number; // seconds
  analysisDepth?: 'basic' | 'detailed' | 'comprehensive';
}

// 🆕 통합 추출 결과 타입
export type UnifiedExtractionResult =
  | VideoExtractionResult
  | WebExtractionResult
  | EnhancedMediaExtractionResult;
